variables:
  MAVEN_CLI_OPTS: "-s ./scenarios-kotlin/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=./scenarios-kotlin/.m2/repository"

stages:
  - build
  - deploy

cache:
  paths:
    - ./scenarios-kotlin/.m2/repository/

build:kotlin:
  stage: build
  image: docker.code-fabrik.com/codefabrik/containers/maven3.6-jdk10adopt
  script:
    - mvn -f scenarios-kotlin/pom.xml ${MAVEN_CLI_OPTS} ${MAVEN_OPTS} clean install

deploy:kotlin:
  stage: deploy
  image: docker.code-fabrik.com/codefabrik/containers/maven3.6-jdk10adopt
#  only:
#    - tag
  script:
    - mvn -f scenarios-kotlin/pom.xml ${MAVEN_CLI_OPTS} ${MAVEN_OPTS} -DdevelopmentVersion=develop-SNAPSHOT -DreleaseVersion=${CI_COMMIT_TAG} -Dresume=false release:prepare release:perform -P cf-nexus-base-url;
