language: java

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: "qQx7jXZye8ohua1qWMi6NN/9U8plRORiqfm/PoXuiXwJvLn1j5qk+O6kluFRbeE3Y/3xIb3P6TpiK9MDCTaSFHtmribXvE1KO122P2FZ27K4Td7G3rVjM5GfGhjStRFavFPlj4mMJav//Q/lHrV8mYo9RbxJThUkjw+7qPZHLUWQE2LSmUJL55gTgTmo0i2sLi3nRY9UkhFV9VqHmQygDqUBBGdHF8lImJEC6IsI2eOiKTEt1An2A+8cl6tQqJdGJp+rM1587Q0hXacRV7UaQ4fsQI89/0hrfg+fZm/s15j7JikCiYmXH3vP9wFSGYVd6z/i8gneviLj8ouafiHg90BpccQNTtWUwTZt8uyqQ9BOXFqUG15qxCTyOG/pFPR2L/TLSxn9qMvGbg1vwut9LNJvUDNPV19nPuls6KURk12wf0J0iESxlgpt3hkzJdQiRPMxmQ0Kl09taUnA1QJiFxfsIEWGGPzuNSS1xdhmnB9ds88oIhLyVYQHR4RnEzRYOoGpRg6XfO6N13TiHrcfc2YGceCZMXy7gdIJcw1MnIOg6jtxORGL+TvNTrCVk/5CrWxQISBFAtOnGV9jZdawNeW6s8FNeL0HDv/Jv3vaUrQwXrFaLKC+umYuBCZhNWDUIxr7KIdU1pWc/9YJM+/bvcR7h9zrjm/Ao15TNmIlmSc="
  file: "target/scenarios-kotlin-$project_version.jar"
  skip_cleanup: true
  on:
    tags: true
  name: $project_version
