language: java

before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: "fDkqeNTI4NnlaZ+81dtjVnV6Z8b2muXgBhi37FrmWA++/IXLpeORyIn8lXRcmQ5BQGoS56W8OBO2SjZLI4g5ur0jYi9YBgdMMPAtpDAVOLGi20JJNMULxjtmWbyriF9j5tSIi1UzUbhqqrWa+w09tDafYzS0/pgJL2nmZ5l5tb2sYJ390oMZg5iGOk+RSwG2p4WLnltn0h4fIlc5a0NzoBN8r4J74BdTBB6xWSc61rBh1i+eVyv1ibIpGgqxpbCMmx3FY1+OFFHRWwKvI7OWBwqp/QqQ3x9h2Vaxuf9oegwq9XHpB8osnvB24YSYAUivhOyHizjN7dq6zlWjTSbBtEgPmqQ0AefDEZjH3sfRQJj4HEfGWqOy9o0/Pbw9Xj2P2iRQZ4zHdTzc7qDk+WSo5XB6YNhlWy1bS86YSufjGJpEokFdV2r+Itx5tSCJkJ607jnYgcVaz6wJr3lyUx7+I3ZIW0aHr2TnoKPldGbaW6Y7UpzUsqiuDnnRJOymBxaOe8uQOleULZFMpyBnnuMOanlPwTjbD6BgI+W1WbD8pGc9JG2UM1cWGBC3VMQoLqPu58AVOIKLVbh8Eob0ek33wijofv9ZSIOathEAaJabzMX+sJMYzZkIc7Mag9mjrdCl8SKuqqJ+QNeAqmuNxBWadP/jiyeUdIbLk20TncCCbpg="
  file: "target/scenarios-kotlin-$project_version.jar"
  skip_cleanup: true
  on:
    tags: true
  name: $project_version
